# Generated by Django 5.1.5 on 2025-04-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('created', models.DateField()),
                ('tag', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('incoming', models.FloatField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.server')),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('critical', 'Critical'), ('medium', 'Medium'), ('low', 'Low')], max_length=100)),
                ('message', models.TextField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.server')),
            ],
        ),
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.FloatField()),
                ('ram', models.FloatField()),
                ('disk', models.FloatField()),
                ('app', models.FloatField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.server')),
            ],
        ),
    ]
